# Generated by Django 2.2 on 2020-02-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ussurl',
            name='shortcode',
            field=models.CharField(blank=True, max_length=120, unique=True),
        ),
    ]
