# Generated by Django 2.2 on 2020-02-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_auto_20200210_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ussurl',
            name='shortcode',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
