# Generated by Django 2.2 on 2020-02-10 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_auto_20200210_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='ussurl',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
