# Generated by Django 2.2 on 2020-02-11 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_ussurl_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ussurl',
            name='shortcode',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
